### PR TITLE
Fix issue #5

### LINKED ISSUE #5: Add ability to name users, and change via command line
It would be ideal if we were able to give an alias for each user, and then change to that use via command line. For example:

```
$ git su meow
```

This would then set the git user and email associated with the alias `meow`.

### PR DESCRIPTION
**Pull request by Techassi**
This fixes #5 

This PR fixes multiple things:

#### Option to modify existing users

```shell
Use the arrow keys to navigate: ↓ ↑ → ←
? Select action:
    Select git user
    Add new git user
    Delete git user
  > Modify git user
```

Following this you can select the user to modify

```shell
? Select git user:
  > Dog <lazy@dog.com>
    [foo] Foo <bar@baz.com>
    [rick] Rick <rick@astley.com>
```

You are then guided through updating each user option (name, email, GPG key ID and alias). Leaving an option empty results in no change for this specific option.

#### Support for aliases

When adding a new user you can specify an alias. This allows you to execute `gitsu <alias>` which immediatly sets the git user.

#### Misc

This commit also adds a default `.gitignore` for Go projects (See [here](https://github.com/github/gitignore/blob/master/Go.gitignore))

I seperated the `git config` commands into their own file and combined the 3 commands into one function called `SetGitConfig`. This cuts down on complexity in the gitsu commands and follows DRY.

#### Note
This improves on #6 and implements the proposed behaviour from @matsuyoshi30 and @BrendanThompson

### CODE REVIEW

**Comment by Techassi** [comment]
Rebased changes from #8 and #9 into this branch. Now able to merge @matsuyoshi30

**Comment by Techassi** [comment]
Any update on this PR @matsuyoshi30 ?

**Comment by matsuyoshi30** [comment]
@Techassi Sorry for the delay. I'll take a look until this weekend :)

File: main.go [hunk 1]
```diff
@@ -37,16 +38,30 @@ func main() {
...
+			fmt.Fprintf(os.Stderr, "Failed to select user: %v\n", err)
+			return 1
+		}
+
+		return 0
+	}
+
 	action := promptui.Select{
 		Label:  "Select action",
 		Items:  []string{sel, add, del},
```
Comment (matsuyoshi30) [inline main.go]: I think it's necessary that `mod` is added into `Items`.

**Review by matsuyoshi30 — CHANGES_REQUESTED** [review]

File: main.go (hunk 1 above)
Comment (Techassi) [reply main.go]: You are 100 percent right. These changes slipped by me while merging the changes from #8 and #9. Will re-add immediately.

Comment (Techassi) [reply main.go]: Updated - marking as resolved.

**Comment by Techassi** [comment]
Were you able to look over the change you requested?

**Review by matsuyoshi30 — APPROVED** [review]

**Comment by matsuyoshi30** [comment]
@Techassi Sorry for the delay again, and thanks for your contribution!

**Comment by Techassi** [comment]
No worries! You are welcome...
